### ISSUE TITLE
light error icon is not light

### ISSUE THREAD

**Issue by rugk** [FirefoxUX/icons#66] opened 2018-04-10 18:35 UTC
STR:
1. Enter `error`.
2. Click "Light".
3. Download.

What happens: 
I get this icon:
![image](https://user-images.githubusercontent.com/11966684/38576404-5323f0b4-3cfe-11e8-882b-d997137bfbbe.png)

What should happen: get light icon

**Comment by bwinton** [comment] 2018-05-18 15:19
This looks like it's been fixed with the switch to the npm-packaged icons. If you can reproduce it, please let me know which icon it fails with!

**Closed by bwinton** 2018-05-18 15:19 UTC
Labels: bug
