### ISSUE TITLE
Use tags instead of categories

### ISSUE THREAD

**Issue by nt1m** [FirefoxUX/icons#44] opened 2017-10-13 15:50 UTC
@shorlander suggested this, and I think it's a good idea.

**Comment by aminalhazwani** [comment] 2017-10-13 15:55
tell me more ☺️

**Comment by nt1m** [comment] 2017-10-13 16:02
@aminalhazwani Icons could have multiple tags for easier identification. The search icon could be tagged with `extensions`, `navigation` since it's used in multiple places.

The arrows could have the `subview` tag they are used for panel subviews. It could also have the `control-center` tag since it's used in the control-center.

This way, if you search a specific tag, you can see all icons that are related to it.

**Comment by brassy-** [comment] 2017-10-16 12:17
I think we discuss this idea with @bwinton already. Personally, I'd love and I think we really need to. 

@nt1m do you have any idea of how to implement this?

**Comment by aminalhazwani** [comment] 2017-10-16 12:19
This is issue is probably a duplicate of #42 ☺️

**Comment by aminalhazwani** [comment] 2018-05-18 12:53
We can close this thanks to this https://github.com/FirefoxUX/photon-icons

**Closed by aminalhazwani** 2018-05-18 12:53 UTC
